Fix the drawText hook
SubRosaCustom/client pull request #12
Opened 2021-12-16 04:51 UTC by checkraisefold

Using some revolutionary assembly that took me a few hours to make and I did not bother commenting it, mainly because MASM is really ass. This is ready to merge, but I need you to review and test on your machine to make sure it doesn't just work on my device. I believe this has some caveats, but with the current calls to drawText Alex does, there should be no problems. This fixes problems with undefined behavior where the varargs weren't being handled properly.
Explanation of the ASM:

pushVarArgs is passed the address of the final argument before the varargs in the hook, and the amount of arguments. ref: https://blog.aaronballman.com/2012/06/how-variable-argument-lists-work-in-c/

It then loops through the arguments given in the hook and pushes them onto the stack after offset 0x48, because offset 0x48 is where the "alpha" argument will be on the stack when calling the original game function.
```
pushVarArgs proc
	readloop:
		mov r8d, dword ptr [rcx + rdx * 8h]
		mov [rsp + 48h + rdx * 8h], r8d
		sub rdx, 1
	jnz readloop
	ret
pushVarArgs endp
```

Because pushVarArgs leaves the stack with information after 0x48, we will get shit tons of runtime errors, stack corruption, and undefined behavior if we don't clear the stack. This is why we have the `clearStack` proc.

The clearStack proc is given the same argument count as the pushVarArgs function, then writes 0x0000 to the values on the stack we previously wrote to. This completely solves our problem of corrupting the stack.
```
clearStack proc
	readloop:
		mov dword ptr [rsp + 48h + rcx * 8h], 0000
		sub rcx, 1
	jnz readloop
	ret
clearStack endp
```

i spent 4.5 hours on this help me god

2021-12-16 04:55 UTC, windows-fryer commented
Wow awesome! I don't care though.

2021-12-16 06:46 UTC, noche-x commented
seems pretty solid, i'll test this to see whats going on linux.

2021-12-20 08:21 UTC, checkraisefold commented
I've added Linux support (UNTESTED. I AM TOO LAZY TO SET UP A TEST ENVIRONMENT, PLEASE TEST IT @noche-x). The only caveat is the end user compiling with MSVC on Windows has to install the VSNASM build customization found at https://github.com/ShiftMediaProject/VSNASM
However, this build customization is well worth it. It is very well made and its only caveat is not being able to step through ASM made with it in the VS debugger, but you can just set a breakpoint in Cheat Engine or x64dbg and step through that way. It gives you detailed error and warning information in the error list, unlike MASM where I have to go digging through the output and looking for the MASM compiler exe's output.

2021-12-20 08:22 UTC, noche-x commented
Going to test this before I PR it.

2021-12-20 12:44 UTC, noche-x commented
With some adjustments it doesn't work..
![pic-window-211220-1521-43](https://user-images.githubusercontent.com/26438306/146768977-cb82d26e-353f-4444-8bd7-7c63ce3770bd.png)
.

2021-12-20 20:45 UTC, noche-x requested changes

2021-12-20 20:45 UTC, noche-x commented on CMakeLists.txt
> +	string(APPEND CMAKE_ASM_NASM_FLAGS "-dUNIX=1")
Causes a compiling error, can be fixed by removing Threads::Threads.

2021-12-20 20:45 UTC, noche-x commented on src/game.hpp
>      std::add_pointer_t<int64_t (char *, int, int, int, float, float, float, float, float, float, float, int)> drawTextFunc;
Linux function signature missing var args.

2021-12-20 20:45 UTC, noche-x commented on src/hooks.cpp
> +extern "C" void __fastcall clearStack(long long count);
Use FASTCALL macro instead of ifdef __win32

2021-12-20 20:45 UTC, noche-x commented on src/hooks.cpp
> +	auto ret = g_game->drawTextFunc(text, params | TEXT_SHADOW, x, y, scale, red, green, blue, alpha);
Only put this and the Windows original function call in ifdefs, because everything else is the same.

2021-12-20 21:04 UTC, checkraisefold commented on CMakeLists.txt
> +	string(APPEND CMAKE_ASM_NASM_FLAGS "-dUNIX=1")
I can't find the source of the threads package or whatever so I don't know why this happens

2022-01-07 05:06 UTC, checkraisefold commented
ready to merge, also fixes msvc compilation
@noche-x for re-review

2022-01-07 05:08 UTC, checkraisefold commented
refuses to inject under windows now? looking into it. suspecting something broke with logger

2022-01-07 05:52 UTC, checkraisefold commented
fixed everything except the main menu text.. the credits menu works, the main menu doesn't render the sub rosa custom text. not sure what changed

2022-01-07 19:43 UTC, noche-x approved these changes
Works correctly on Linux, compiles, everything seems fine.

2022-01-07 19:43 UTC, merged